/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorswing;

/**
 *
 * @author HP
 */
public class Calculator extends javax.swing.JFrame {

    private int operation;
    
    public Calculator() {
        initComponents();
        this.operation=1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LabelHeader = new javax.swing.JLabel();
        LabelFnum = new javax.swing.JLabel();
        LabelSnum = new javax.swing.JLabel();
        tfFnum = new javax.swing.JTextField();
        tfSnum = new javax.swing.JTextField();
        LabelOperation = new javax.swing.JLabel();
        RadioAdd = new javax.swing.JRadioButton();
        RadioDivision = new javax.swing.JRadioButton();
        RadioMultiplication = new javax.swing.JRadioButton();
        RadioSubtract = new javax.swing.JRadioButton();
        btnReset = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        LabelResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelHeader.setText("Calculator");

        LabelFnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelFnum.setText("First Number");

        LabelSnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelSnum.setText("Second Number");

        tfFnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFnumActionPerformed(evt);
            }
        });

        LabelOperation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelOperation.setText("Select Operation");

        buttonGroup1.add(RadioAdd);
        RadioAdd.setText("Addition");
        RadioAdd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioAddStateChanged(evt);
            }
        });

        buttonGroup1.add(RadioDivision);
        RadioDivision.setText("Division");
        RadioDivision.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioDivisionStateChanged(evt);
            }
        });

        buttonGroup1.add(RadioMultiplication);
        RadioMultiplication.setText("Multiplication");
        RadioMultiplication.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioMultiplicationStateChanged(evt);
            }
        });

        buttonGroup1.add(RadioSubtract);
        RadioSubtract.setText("Subtraction");
        RadioSubtract.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioSubtractStateChanged(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        LabelResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelResult)
                        .addContainerGap(620, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioAdd)
                                .addGap(18, 18, 18)
                                .addComponent(RadioSubtract)
                                .addGap(29, 29, 29)
                                .addComponent(RadioMultiplication)
                                .addGap(30, 30, 30)
                                .addComponent(RadioDivision))
                            .addComponent(LabelOperation)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelFnum)
                                    .addComponent(LabelSnum))
                                .addGap(188, 188, 188)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfSnum, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfFnum, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelHeader)
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(btnCalculate)
                    .addContainerGap(533, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelHeader)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFnum)
                    .addComponent(tfFnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelSnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSnum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelOperation)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioAdd)
                    .addComponent(RadioSubtract)
                    .addComponent(RadioMultiplication)
                    .addComponent(RadioDivision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(LabelResult)
                .addGap(36, 36, 36)
                .addComponent(btnReset)
                .addGap(68, 68, 68))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(308, Short.MAX_VALUE)
                    .addComponent(btnCalculate)
                    .addGap(70, 70, 70)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfFnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFnumActionPerformed

    private void RadioAddStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioAddStateChanged
        if(RadioAdd.isSelected())
            this.operation=1;
    }//GEN-LAST:event_RadioAddStateChanged

    private void RadioSubtractStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioSubtractStateChanged
        if(RadioSubtract.isSelected())
            this.operation=2;
    }//GEN-LAST:event_RadioSubtractStateChanged

    private void RadioMultiplicationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioMultiplicationStateChanged
         if(RadioMultiplication.isSelected())
            this.operation=3;
    }//GEN-LAST:event_RadioMultiplicationStateChanged

    private void RadioDivisionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioDivisionStateChanged
        if(RadioDivision.isSelected())
            this.operation=4;
    }//GEN-LAST:event_RadioDivisionStateChanged

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try{
        float f1 = Float.parseFloat(tfFnum.getText());
        float f2 = Float.parseFloat(tfSnum.getText());
        float f3 = 0;
        switch(this.operation){
            case 1:
                f3 = f1+f2;
                break;
            case 2:
                f3 = f1-f2;
                break;
            case 3:
                f3 = f1*f2;
                break;
            case 4:
                f3=f1/f2;
                break;
        }
        LabelResult.setText("Result : "+f3);
        }
        catch(NumberFormatException ex){
            LabelResult.setText("Please Enter Numbers Only");
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        tfFnum.setText("");
        tfSnum.setText("");
        LabelResult.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFnum;
    private javax.swing.JLabel LabelHeader;
    private javax.swing.JLabel LabelOperation;
    private javax.swing.JLabel LabelResult;
    private javax.swing.JLabel LabelSnum;
    private javax.swing.JRadioButton RadioAdd;
    private javax.swing.JRadioButton RadioDivision;
    private javax.swing.JRadioButton RadioMultiplication;
    private javax.swing.JRadioButton RadioSubtract;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField tfFnum;
    private javax.swing.JTextField tfSnum;
    // End of variables declaration//GEN-END:variables
}
